### ISSUE TITLE
muuru darkness is missing

### ISSUE THREAD

**Issue by Cure-whitemane** [broizter/DBM-Whitemane#3]
Per the title on the last addon version muuru' darkness is missing - not showing in dbm

**Comment by Cure-whitemane** [comment]
I mean it literally missing in DBM announcement

**Comment by broizter** [comment]
It worked when I did M'uru with the latest version the other day. Maybe something has changed server side. I will collect a Transcriptor log next time I go there to see what is going on.

**Comment by Cure-whitemane** [comment]
@broizter I have combat logs. I can share it

**Comment by Cure-whitemane** [comment]
[WoWCombatLog.zip](https://github.com/user-attachments/files/16319770/WoWCombatLog.zip)

**Comment by broizter** [comment]
That is interesting. The event that triggers darkness alert is missing from the combat log. I will double check it when I go Sunwell (probably today) but it seems like something changed server side indeed. If that is the case I will report it upstream.

**Comment by broizter** [comment]
Was not able to reproduce. Probably temporary server bug.
