### ISSUE TITLE
Unbalancing strike timer on Thorim not showing

### ISSUE THREAD

**Issue by ottovonwulffen** [broizter/DBM-Whitemane#6]
The countdown timer for unbalancing strike on hodir is not showing up, even when tanking. There seems to be something off with

local timerUnbalancingStrike		= mod:NewCDTimer(25.6, 62130, nil, "Tank", nil, 5, nil, DBM_CORE_L.TANK_ICON)

Because the other portion of it - the warning for when it's applied to the other tank to taunt the boss, is working. I.e., this:
 
	elseif spellId == 62130 then				-- Unbalancing Strike
		if args:IsPlayer() then
			specWarnUnbalancingStrikeSelf:Show()
			specWarnUnbalancingStrikeSelf:Play("defensive")
		else
			specWarnUnbalancingStrike:Show(args.destName)
			specWarnUnbalancingStrike:Play("tauntboss")
		end

**Comment by broizter** [comment]
The timer is disabled by default. Did you enable it? 
![bild](https://github.com/user-attachments/assets/b76a4e31-4943-4433-96f6-f357fcf9151a)

**Comment by ottovonwulffen** [comment]
Ah I'm an idiot, didn't think to check this, thought it would be enabled by default for tanks. Thanks for the quick reply and sorry for the bogus bug report!

**Comment by broizter** [comment]
Don't worry about it. I think it was a fair assumption it would enabled by default and you described the issue you were having well.
